export const TutorActions = {
    /**
     * School Subjects
     */
    LIST_SCHOOL_SUBJECTS: "LIST_SCHOOL_SUBJECTS",
    CREATE_SCHOOL_SUBJECT: "CREATE_SCHOOL_SUBJECT",
    UPDATE_SCHOOL_SUBJECT: "UPDATE_SCHOOL_SUBJECT",
    DELETE_SCHOOL_SUBJECT: "DELETE_SCHOOL_SUBJECT",


    /**
     * University Modules
     */
    LIST_UNIVERSITY_MODULES: "LIST_UNIVERSITY_MODULES",
    CREATE_UNIVERSITY_MODULE: "CREATE_UNIVERSITY_MODULE",
    UPDATE_UNIVERSITY_MODULE: "UPDATE_UNIVERSITY_MODULE",
    DELETE_UNIVERSITY_MODULE: "DELETE_UNIVERSITY_MODULE",
}