export const StudentActions = {
    /**
     * Student Profile
     */
    SHOW_STUDENT_PROFILE: "SHOW_STUDENT_PROFILE",
    CREATE_STUDENT_PROFILE: "CREATE_STUDENT_PROFILE",
    UPDATE_STUDENT_PROFILE: "UPDATE_STUDENT_PROFILE",
    DELETE_STUDENT_PROFILE: "DELETE_STUDENT_PROFILE",


    /**
     * Student Tutoring Requests
     */
    GET_STUDENT_TUTORING_REQUESTS: "GET_STUDENT_TUTORING_REQUESTS",
    CREATE_STUDENT_TUTORING_REQUEST: "CREATE_STUDENT_TUTORING_REQUEST",
    CANCEL_STUDENT_TUTORING_REQUEST: "CANCEL_STUDENT_TUTORING_REQUEST",


    /**
     * Student Queries
     */
    SEARCH_FOR_TUTORS: "SEARCH_FOR_TUTORS",
}