export const TutorActions = {
    /**
     * Tutor Profile
     */
    SHOW_TUTOR_PROFILE: "SHOW_TUTOR_PROFILE",
    CREATE_TUTOR_PROFILE: "CREATE_TUTOR_PROFILE",
    UPDATE_TUTOR_PROFILE: "UPDATE_TUTOR_PROFILE",
    DELETE_TUTOR_PROFILE: "DELETE_TUTOR_PROFILE",


    /**
     * Tutor Advertisements
     */
    LIST_TUTOR_ADVERTISEMENTS: "LIST_TUTOR_ADVERTISEMENTS",
    SHOW_TUTOR_ADVERTISEMENT: "SHOW_TUTOR_ADVERTISEMENT",
    CREATE_TUTOR_ADVERTISEMENTS: "CREATE_TUTOR_ADVERTISEMENT",
    UPDATE_TUTOR_ADVERTISEMENT: "UPDATE_TUTOR_ADVERTISEMENT",
    DELETE_TUTOR_ADVERTISEMENT: "DELETE_TUTOR_ADVERTISEMENT",

    /**
     * Tutor Tutoring Requests
     */
    GET_TUTOR_TUTORING_REQUESTS: "GET_TUTOR_TUTORING_REQUESTS",
    TUTOR_ACCEPT_TUTORING_REQUEST: "TUTOA_ACCEPT_TUTORING_REQUEST",
    TUTOR_REJECT_TUTORING_REQUEST: "TUTOR_REJECT_TUTORING_REQUEST",
}